from asyncio import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMainWindow, QInputDialog
from oracle_config import Ora
from label_print import GenLabel
import os 
import win32print, win32api
from about_page import Ui_about_page
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.





class Ui_MainWindow(Ui_about_page):

    def __init__(self) -> None:
        super(Ui_MainWindow,self).__init__()
        self.about_page = QtWidgets.QDialog()
        self.about_ui = Ui_about_page()
        self.about_ui.setupUi(self.about_page)
                


        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 456)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uhid = QtWidgets.QLineEdit(self.centralwidget)
        self.uhid.setGeometry(QtCore.QRect(130, 10, 211, 41))
        self.uhid.setInputMask("")
        self.uhid.setMaxLength(12)
        self.uhid.setFrame(True)
        self.uhid.setDragEnabled(False)
        self.uhid.setPlaceholderText("")
        self.uhid.setObjectName("uhid")


        self.enter_uhid_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_uhid_label.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.enter_uhid_label.setFont(font)
        self.enter_uhid_label.setTextFormat(QtCore.Qt.PlainText)
        self.enter_uhid_label.setObjectName("enter_uhid_label")


        self.click_to_view_button = QtWidgets.QPushButton(self.centralwidget)
        self.click_to_view_button.setGeometry(QtCore.QRect(350, 0, 211, 61))


        self.click_to_view_button.clicked.connect(lambda :self.get_data_to_display(self.uhid.text().upper()))


        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imageResources/click_to_view_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.click_to_view_button.setStyleSheet("background-image:url('imageResources/click_to_view_button.png');border:none;")
        #self.click_to_view_button.setIcon(icon)
        #self.click_to_view_button.setIconSize()
     

        self.tableView = QtWidgets.QTableWidget(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 90, 571, 191))
        self.tableView.setObjectName("tableView")
        
        
        self.tableView.setColumnCount(6)
        self.tableView.setHorizontalHeaderLabels([
            
            "Patient ID","Patient Name", "Gender",
            "Age", "Consultant Name", "Order Name",
            
            ])
        header = self.tableView.horizontalHeader()
        for i in range(0,6):
            header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
            #header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        
        self.tableView.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        

        

        # col = 0
        # item = []

        # for items in self.print_values:

        #     print(items)

        # for data in items:
        #     print(data)            
        #     cell = QtWidgets.QTableWidgetItem(str(data))
        #     self.tableView.setItem(self.row_pos,col,cell)
        #     self.tableView.insertRow(self.row_pos)
        #     col += 1
        




        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 236, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imageResources/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setStyleSheet("background-image:url('imageResources/download.png');border:none;")
        #self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.generate_label)


        self.print_button = QtWidgets.QPushButton(self.centralwidget)
        self.print_button.setGeometry(QtCore.QRect(520, 300, 80, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imageResources/print_button1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.print_button.setStyleSheet("background-image:url('imageResources/print_button1.png');border:none;")
        self.print_button.clicked.connect(self.direct_print)

        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(345, 300, 80, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imageResources/reset_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.reset_button.setStyleSheet("background-image:url('imageResources/reset_button.png');border:none;")
        self.reset_button.clicked.connect(self.clear_table)
        
        #self.print_button.setIcon(icon2)

        self.print_button.setObjectName("print_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 20))
        self.menubar.setObjectName("menubar")
        self.menuHOME = QtWidgets.QMenu(self.menubar)
        self.menuHOME.setObjectName("menuHOME")
        self.menuABOUT = QtWidgets.QMenu(self.menubar)
        self.menuABOUT.setObjectName("menuABOUT")


        goto_action = QtWidgets.QAction('About Page', self.menubar)
        goto_action.triggered.connect(lambda:self.about_page.show())
        self.menuABOUT.addAction(goto_action)


        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHOME.menuAction())
        self.menubar.addAction(self.menuABOUT.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nuclear Label Print"))
        MainWindow.setWindowIcon(QtGui.QIcon('imageResources/logo.ico'))
        self.uhid.setText(_translate("MainWindow", "KH1000"))
        self.enter_uhid_label.setText(_translate("MainWindow", "Enter UHID"))
        self.click_to_view_button.setText(_translate("MainWindow", " "))
        self.pushButton.setText(_translate("MainWindow", " "))
        self.print_button.setText(_translate("MainWindow", " "))
        self.menuHOME.setTitle(_translate("MainWindow", "HOME"))
        self.menuABOUT.setTitle(_translate("MainWindow", "ABOUT"))

    
    def get_data_to_display(self,uhid_value):
        # uhid_value = self.uhid_value
        self.database = Ora()
        self.print_value = self.database.get_label_data(uhid_value)
               
        self.tableView.setRowCount(len(self.print_value))
        self.row_in_table = 0

        for rows in self.print_value:
            self.tableView.setItem(self.row_in_table,0,QtWidgets.QTableWidgetItem(str(rows[0])))
            self.tableView.setItem(self.row_in_table,1,QtWidgets.QTableWidgetItem(str(rows[1])))
            self.tableView.setItem(self.row_in_table,2,QtWidgets.QTableWidgetItem(str(rows[2])))
            self.tableView.setItem(self.row_in_table,3,QtWidgets.QTableWidgetItem(str(rows[3])))
            self.tableView.setItem(self.row_in_table,4,QtWidgets.QTableWidgetItem(str(rows[4])))
            self.tableView.setItem(self.row_in_table,5,QtWidgets.QTableWidgetItem(str(rows[5])))
            self.row_in_table += 1

    def generate_label(self):
        #self.file_url = QFileDialog.getSaveFileName()
        #self.file_url = self.file_url[0]
        
        #if ".pdf" in self.file_url:
        #    pass
        #else:
        #    self.file_url += ".pdf"
        self.replace_external()
        self.label = GenLabel("Label.pdf",self.print_value,self.manual_dr_name)

        os.startfile("Label.pdf")   




    def clear_table(self):
        while self.tableView.rowCount() > 0:
            self.tableView.removeRow(0)




    def direct_print(self):
        self.label = GenLabel("Label.pdf",self.print_value)
        GHOSTSCRIPT_PATH = r"GHOSTSCRIPT\bin\gswin32.exe"
        GSPRINT_PATH = r"GSPRINT\gsprint.exe"
        currentprinter = win32print.GetDefaultPrinter()
        win32api.ShellExecute(0, 'open', GSPRINT_PATH, '-ghostscript "'+GHOSTSCRIPT_PATH+'" -printer "'+currentprinter+'" "Label.pdf"', '.', 0)

    def replace_external(self):
        self.manual_dr_name , pressed = QInputDialog.getText(self.centralwidget, "Input Dr. Name", "Text: ",
                                            QtWidgets.QLineEdit.Normal, "")
        if pressed:
            return (self.manual_dr_name)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
